### PR TITLE
disable -Werror by default (but still use it for continuous integration)

### LINKED ISSUE #440: Unused variables breaking build
Hello.

Using the default compiler (gcc (GCC) 5.1.0) on an up-to-date Arch Linux install, a plain `make` of 6ace3b655cf13dbd1e23b2535c51abf3305fea63 with no parameters results in:

```
compiling build/linux-x86_64/machine.o
In file included from src/avian/processor.h:18:0,
                 from src/avian/machine.h:21,
                 from src/avian/jnienv.h:14,
                 from src/machine.cpp:11:
src/avian/bootimage.h:64:17: error: ‘vm::TargetBootFlatConstant’ defined but not used [-Werror=unused-variable]
 #define NAME(x) Target##x
                 ^
src/bootimage-template.cpp:6:16: note: in expansion of macro ‘NAME’
 const unsigned NAME(BootFlatConstant) = 1 << NAME(BootShift);
                ^
src/avian/bootimage.h:64:17: error: ‘vm::TargetBootHeapOffset’ defined but not used [-Werror=unused-variable]
 #define NAME(x) Target##x
                 ^
src/bootimage-template.cpp:7:16: note: in expansion of macro ‘NAME’
 const unsigned NAME(BootHeapOffset) = 1 << (NAME(BootShift) + 1);
                ^
In file included from src/avian/processor.h:18:0,
                 from src/avian/machine.h:21,
                 from src/avian/jnienv.h:14,
                 from src/machine.cpp:11:
src/bootimage-template.cpp:6:21: error: ‘vm::BootFlatConstant’ defined but not used [-Werror=unused-variable]
 const unsigned NAME(BootFlatConstant) = 1 << NAME(BootShift);
                     ^
src/avian/bootimage.h:70:17: note: in definition of macro ‘NAME’
 #define NAME(x) x
                 ^
src/bootimage-template.cpp:7:21: error: ‘vm::BootHeapOffset’ defined but not used [-Werror=unused-variable]
 const unsigned NAME(BootHeapOffset) = 1 << (NAME(BootShift) + 1);
                     ^
src/avian/bootimage.h:70:17: note: in definition of macro ‘NAME’
 #define NAME(x) x
                 ^
cc1plus: all warnings being treated as errors
makefile:1804: recipe for target 'build/linux-x86_64/machine.o' failed
make: *** [build/linux-x86_64/machine.o] Error 1
```

I'm guessing this version of gcc produces more warnings than the developer(s) compilers, and the `-Werror` flag is causing issues here.

### PR DESCRIPTION
**Pull request by dicej**
Since we can't predict what warnings future compilers will emit, and
most people just want to build Avian without some new warning tripping
it up, we now omit -Werror unless requested via the "use-werror=true"
option to make.  Note that we pass "use-werror=true" in test/ci.sh to
ensure Travis alerts us to new warnings as they appear.

BTW, sorry about the unrelated whitespace changes in this patch; I've
got Emacs set up to fix whitespace "problems" on save, and those are
what it found.

Fixes #440 (except I wasn't able to reproduce the latest warnings)

### CODE REVIEW

File: test/ci.sh [hunk 1]
```diff
@@ -4,7 +4,7 @@ set -eo pipefail
 
 root_dir=$(pwd)
 
-flags="${@}"
+flags="use-werror=true ${@}"
```
Comment (joshuawarner32) [inline test/ci.sh]: Did you mean `use-werror=true` instead?

Comment (dicej) [inline test/ci.sh]: Yes, and I realized that right after I opened the PR :)  Please see the the
new commit.
